### ISSUE TITLE
clematis panics if Metadata doesn't have xesam:url

### ISSUE THREAD

**Issue by reesypiece** [TorchedSammy/Clematis#2]
trying to run Clematis gives me 
```
Getting information from "cmus"
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
main.setPresence(0xc057de56821c1643, {0xc057de56821c1643, 0xfffffffc8a0095e5, 0x6788a0})
	/home/jelly/Clematis/main.go:114 +0x4d4
main.main()
	/home/jelly/Clematis/main.go:69 +0x8c5
```

looking at the line that panics out, it seems that cmus doesn't want to expose any of my files' `xesam:url`. 

entering `dbus-send --print-reply --dest=org.mpris.MediaPlayer2.cmus /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'` into my shell gives me, for example,
```
method return time=1635713510.349210 sender=:1.47 -> destination=:1.90 serial=67 reply_serial=2
   variant       array [
         dict entry(
            string "mpris:trackid"
            variant                object path "/31"
         )
         dict entry(
            string "mpris:length"
            variant                int64 238000000
         )
         dict entry(
            string "xesam:artist"
            variant                array [
                  string "aespa"
               ]
         )
         dict entry(
            string "xesam:title"
            variant                string "Savage"
         )
         dict entry(
            string "xesam:album"
            variant                string "Savage - The 1st Mini Album"
         )
         dict entry(
            string "xesam:albumArtist"
            variant                array [
                  string "aespa"
               ]
         )
         dict entry(
            string "xesam:genre"
            variant                array [
                  string "댄스/팝"
               ]
         )
         dict entry(
            string "xesam:comment"
            variant                array [
                  string "32349594"
               ]
         )
         dict entry(
            string "xesam:trackNumber"
            variant                int32 2
         )
         dict entry(
            string "xesam:discNumber"
            variant                int32 1
         )
      ]
```

~~i think i might have a fix but i feel like it's a bandaid fix and it might suck ^^;~~

**Comment by TorchedSammy** [comment]
hmm
thats odd, as i am also using cmus and get `xesam:url`. i could just make clematis get that after checking if title is sent

**Comment by TorchedSammy** [comment]
i just did the check for it like the other keys which should fix it

**Comment by reesypiece** [comment]
fix confirmed working, ty!
