### ISSUE TITLE
panic: interface conversion: interface {} is nil, not int64

### ISSUE THREAD

**Issue by paper42** [TorchedSammy/Clematis#5]
```
%: ./Clematis
Getting information from Mozilla Firefox
panic: interface conversion: interface {} is nil, not int64

goroutine 1 [running]:
main.setPresence(0xc065a28c29b7a0b9, {0xc065a28c29b7a0b9, 0x38e123b6e, 0x676840}, 0xc000123f08)
	/home/user/go/pkg/mod/github.com/!torched!sammy/!clematis@v0.2.0/main.go:130 +0x585
main.main()
	/home/user/go/pkg/mod/github.com/!torched!sammy/!clematis@v0.2.0/main.go:68 +0x4e6
```

**Comment by TorchedSammy** [comment]
i hate dbus and i hate godbus

**Comment by TorchedSammy** [comment]
seems that firefox doesnt send length and clematis doesnt check for that, will fix
